version: '2.4'

services:
  octoprint_1:
    container_name: octoprint_1
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 8001:5000
    devices:
     - /dev/printer_prusa_1:/dev/ttyACM0
    volumes:
     - ./octoprint_1:/octoprint

  # octoprint_2:
  #   container_name: octoprint_2
  #   image: octoprint/octoprint
  #   restart: unless-stopped
  #   ports:
  #     - 8002:5000
  #   devices:
  #    - /dev/printer_prusa_2:/dev/ttyACM0
  #   volumes:
  #    - ./octoprint_2:/octoprint

  # octoprint_3:
  #   container_name: octoprint_3
  #   image: octoprint/octoprint
  #   restart: unless-stopped
  #   ports:
  #     - 8003:5000
  #   devices:
  #    - /dev/printer_prusa_3:/dev/ttyACM0
  #   volumes:
  #    - ./octoprint_3:/octoprint

  # octoprint_4:
  #   container_name: octoprint_4
  #   image: octoprint/octoprint
  #   restart: unless-stopped
  #   ports:
  #     - 8004:5000
  #   devices:
  #    - /dev/printer_prusa_4:/dev/ttyACM0
  #   volumes:
  #    - ./octoprint_4:/octoprint

